### ISSUE TITLE
Depending on the JRE version/implementation used, PackUpdate has issues finding JavaFX

### ISSUE THREAD

**Issue by Laikar** [XDjackieXD/PackUpdate#23] opened 2019-07-02 18:53 UTC
I have tried to import the project onot IntelliJ to build it myself since the latest build is form last year, but i can't get to do properly.
I have installed the scala plugin, but when importing i get the follwing error multiple times:
```
error: error while loading String, class file '/modules/java.base/java/lang/String.class' is broken
(class java.lang.NullPointerException/null)
```
And when trying to assemble, all of the JavaFX classes return a not found error (even when manually adding [javaFX](https://openjfx.io/) as a library)

**Comment by Kilobyte22** [comment] 2019-07-03 09:59
The issue with javafx is one I'm having myself, my current "solution" is to use Java 8 for building. The other error I've never seen myself. What operating system, version of intellij and version of Scala are you using?

**Comment by Laikar** [comment] 2019-07-05 10:21
I'm on windows 10, and using the latest stable Version of IntelliJ (i think?) 2019.1.3 and i'm using the Scala plugin on IntelliJ plugin marketplace

**Comment by Laikar** [comment] 2019-07-07 18:57
I kinda solved the weird error by using [openjdk](https://adoptopenjdk.net/), but the JavaFX problem still persists, i have managed to import it so that the IDE recognizes the library, but when running assembly it still can't found it, both on openJDK 8 and 12, how do you run it with 9 so that it gives no errors?

**Comment by Laikar** [comment] 2019-07-07 20:24
Also managed to finally build it after 2 hours of Java library hell by adding this to to build.sbt
```
val os = "win" //"mac","linux" or "win"
val javafxVersion = "12.0.1"
val javafxModules = Seq(
  "javafx-base",
  "javafx-controls",
  "javafx-fxml",
  "javafx-graphics"
)

assemblyMergeStrategy in assembly := {
  case PathList("META-INF", xs @ _*) => MergeStrategy.discard
  case x => MergeStrategy.first
}
```
I found this code on [this reddit post](https://www.reddit.com/r/scala/comments/bn5w2f/javafx_and_scala/) and just changed the version and OS, i suggest looking at[ this other post](https://www.reddit.com/r/scala/comments/9fbzbk/build_file_snippet_for_using_javafx_with_java_11/) for doing the OS selection.

**Comment by Kilobyte22** [comment] 2019-07-24 18:12
Thanks for the pointers, will look into this later

**Comment by Kilobyte22** [comment] 2019-07-24 22:06
One problem i see with your solution is that it requires me to ship different binaries for different platforms. This is obviously undesirable. I do have an idea though. PackUpdate recently gained the ability to download maven artifacts at runtime (it needs this for Forge installation). I can use that functionality to download the correct binary for the current platform at runtime.

**Comment by Kilobyte22** [comment] 2019-07-29 19:04
After trying a lot of hacks to get JavaFX working realiably, i decided to replace it with swing. This should be finished with commit 098810b. Can you please verify that the issue is solved?

**Comment by Laikar** [comment] 2019-08-07 13:58
Yeah, it imports correctly now. The string.class is broken error only happens when using openjdk-12
```
error: error while loading String, class file '/modules/java.base/java/lang/String.class' is broken
(class java.lang.NullPointerException/null)
```

On openjdk-8 everything imports fine, so i suggest adding it to the readme.

**Comment by Kilobyte22** [comment] 2019-10-30 19:00
Has been fixed by replacing JavaFX by Swing. Mind verifying again if it works now?

**Comment by Kilobyte22** [comment] 2020-02-29 15:03
I sadly was not able to reproduce this issue, neither with 12 nor with the current release 13. Could that be an issue on your end?

**Comment by Kilobyte22** [comment] 2021-01-28 16:25
As there hasn't been anything happening i'll now close this. If the issue continues, please inform me, and i'm happy to reopen

**Closed as completed by Kilobyte22** 2021-01-28 16:25 UTC
