### ISSUE TITLE
since a couple of days Packupdate doesn't work with curseforge anymore

### ISSUE THREAD

**Issue by zISKo666** [XDjackieXD/PackUpdate#19] opened 2018-12-18 18:33 UTC
Hi,

I'm using Packupdate since a few years now and never had any issues with it.
But now the downloads from Curseforge seams to be broken because I always get empty files.
Download the mods from another location is working still fine.
I know you are no longer maintaining this project, so I've tried to fix it on my own but because I have no knowledge about this stuff I failed.

Any help or a fix for this issue would be very welcome.

**Comment by kencinder** [comment] 2018-12-27 17:08
Same problem here, downloading via the link on a projects page works fine, so I think it may be as simple as User Agent being checked.

**Comment by comp500** [comment] 2018-12-27 21:37
It seems to be due to user agent checking. I proxied the connection with Fiddler and got a CloudFlare block page saying "The owner of this website (minecraft.curseforge.com) has banned your access based on your browser's signature (48fecdcb7e776a2b-ua21).".

The links from the unofficial Curse api (e.g. https://files.forgecdn.net/files/2606/737/demagnetize-1.12.2-1.0.0.2.jar) work fine, however. These links can be obtained from the usual links on the website as the normal links redirect to the unofficial links, and the blocking is only done at the official links.

These links can be obtained by using a website like https://httpstatus.io/ or by obtaining the link from your browser, as follows:

In Firefox, download the file, then click the download history button (or Ctrl+J), then right click the file and click "Copy Download Link":
![image](https://user-images.githubusercontent.com/1138417/50495003-71706a00-0a1e-11e9-9c13-5509f3e449eb.png)

In Chrome, download the file, then go to `chrome://downloads`. The link should be displayed:
![image](https://user-images.githubusercontent.com/1138417/50495087-e348b380-0a1e-11e9-8bba-3eb2008d5daf.png)

In Edge, download the file, then click the Hub button (star icon). Right click the download and select "Report that this download is unsafe". You can then copy the link from the webpage that appears.
![image](https://user-images.githubusercontent.com/1138417/50495163-56522a00-0a1f-11e9-86c9-5d9601129bfa.png)

**Comment by zISKo666** [comment] 2018-12-30 12:06
Hi,

After you guys pointed me to the 403 error, I found a solution for this issue and made a pull-request.
https://github.com/XDjackieXD/PackUpdate/pull/20/commits/d9ed876770fa2566f646fab0fdcef9326edfc036

_... and I learned a bit more about java programming!_

**Comment by kencinder** [comment] 2019-01-16 13:54
Appears PR merged for this, can we get a build?

**Comment by zISKo666** [comment] 2019-01-16 17:40
I put a working version of [PackUpdate.jar](https://www.dropbox.com/s/5ndh0zusprmraac/PackUpdate.jar?dl=1) to my Dropbox.

**Comment by kencinder** [comment] 2019-10-05 14:30
Seems they've done something again, causing 403 errors with downloads. The link's work fine from within a browser.

**Comment by zISKo666** [comment] 2019-10-07 16:50
Having the same issue but found no solution to fix it.
I can click a link in outlook that works but the same link in excel does not.

**Comment by kencinder** [comment] 2019-10-12 15:57
From what I can tell, it looks like they're checking headers now.

**Comment by zISKo666** [comment] 2019-10-12 19:27
It seams that we have to use the Twitch API now.
https://dev.twitch.tv/docs/v5/
But i am to stupid to find out how to use it.

**Comment by kencinder** [comment] 2019-10-14 01:53
You can still pull links from forgecdn as referenced in https://github.com/XDjackieXD/PackUpdate/issues/19#issuecomment-450235550, which is a pain in the butt...but could be worse.

**Comment by Kilobyte22** [comment] 2019-10-30 19:02
I'll see what i can do to make this work with CurseForge again. This seems to be a recurring Problem

**Comment by zISKo666** [comment] 2019-11-29 14:43
Hey, I'm wondering if there is any update to this issue?

Kind regards
zISKo666

**Comment by Kilobyte22** [comment] 2020-02-29 02:38
Actually no, sorry. I took a break from the project. I'll see if I can figure this out tomorrow.

**Comment by entropiccode** [comment] 2020-04-21 08:41
This appears to still be a problem, with version 3.0.1 throwing 403 errors when using curseforge links.

**Comment by Kilobyte22** [comment] 2020-04-24 13:12
The problem is that CurseForge is actively trying to prevent us from downloading their mods in an automated fashion. I have tried implementing a working solution, however no success ...yet. It used to be as easy as faking your User-Agent string to be something that looks like a web browser. However it seems that now you need the correct cookies from a previous request - and possibly even more. I still have a bit of trouble with getting this all working and it likely will be fragile, so the next change could break everything. Also i'm am looking into how the official curse/twitch app does it - so maybe that would be another solution. The downside is that this is probably quite a bit more work, even though it would likely be a more stable solution.

**Comment by Kilobyte22** [comment] 2020-04-24 18:01
I found a possible workaround:

When a typical curseforge link gets downloaded (lets take for example https://www.curseforge.com/minecraft/mc-mods/openradio/download/2443569/file) it actually redirects twice after that, resulting in a URL on the domain media.forgecdn.net (sticking with the example that would be https://media.forgecdn.net/files/2443/569/OpenRadio-0.9.5-MC1.11.2.jar). @XDjackieXD pointed out to me that using the media.forgecdn.net link actually works flawlessly - so im am proposing that as a workaround.
The easiest way of getting this link i can think of right now would be to download the file, then right-click it in the download manager and click `Copy Download Link` (assuming you use Firefox)

**Closed as completed** 2021-12-13 11:41 UTC
